### PR TITLE
Use Emacs url package and support unsaved buffers

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by lassik** [comment]
Your old url code was almost working. It was using `let` instead of `let*` so the headers didn't take effect, and `url-retrieve-synchronously` included the HTTP headers in the output buffer which confused the JSON parser. `url-insert-file-contents` is an easier function that skips the headers.

Anyway, great package! I was surprised it was possible to accomplish a validator in Emacs with so little code.

**Comment by lassik** [comment]
Force-pushed to resolve merge conflict.

**Comment by arthurgleckler** [comment]
Thanks.

I already had an almost-working conversion to use url-retrieve in the other branch, so I'm going with that because I had restructured the code in the process.  However, thanks for pointing out url-insert-file-contents.  That was the key I needed to get it working.  (I credit you in this and other commit comments.)

The code to handle unsaved buffers doesn't work because Compilation mode needs an actual filename.  I now report an error for unsaved buffers.

I added the autoload declaration and the message when there are no errors or warnings.

**Comment by mnieper** [comment]
The `compile` command of Emacs asks when there are unsaved buffers. Maybe you can reuse this code/copy this behavior.

**Comment by arthurgleckler** [comment]
> The `compile` command of Emacs asks when there are unsaved buffers. Maybe you can reuse this code/copy this behavior.

That's for buffers that have files but haven't been saved.  That's already handled because I send the buffer contents, not the file contents.  The problem is that buffers that have never been saved don't work with Compilation mode.

**Comment by arthurgleckler** [comment]
Please see the latest version.

**Comment by lassik** [comment]
> I already had an almost-working conversion to use url-retrieve in the other branch, so I'm going with that because I had restructured the code in the process.

Sure.

> The code to handle unsaved buffers doesn't work because Compilation mode needs an actual filename. I now report an error for unsaved buffers.

It doesn't need a filename. But the key binding that jumps to an error maybe does.

> > The `compile` command of Emacs asks when there are unsaved buffers. Maybe you can reuse this code/copy this behavior.
> 
> That's for buffers that have files but haven't been saved. That's already handled because I send the buffer contents, not the file contents.

Correct.

> I added the autoload declaration and the message when there are no errors or warnings.

Thanks.

**Pull request closed without merging**
